from .post_comments import POST_COMMENT_TEXT_MAX_LENGTH, POST_COMMENT_TEXT_MIN_LENGTH
from .posts import POST_TEXT_MAX_LENGTH, POST_TEXT_MIN_LENGTH

__all__ = (
    'POST_COMMENT_TEXT_MAX_LENGTH',
    'POST_COMMENT_TEXT_MIN_LENGTH',
    'POST_TEXT_MAX_LENGTH',
    'POST_TEXT_MIN_LENGTH',
)
