CHANNEL_NAME_MIN_LENGTH = 1
CHANNEL_NAME_MAX_LENGTH = 100

CHANNEL_SLUG_MIN_LENGTH = 1
CHANNEL_SLUG_MAX_LENGTH = 40

CHANNEL_EMAIL_MAX_LENGTH = 255

CHANNEL_DESCRIPTION_MAX_LENGTH = 1000

CHANNEL_COUNTRY_MAX_LENGTH = 40
