"""new checkconstraing for self subscriptions and new videos index

Revision ID: 07869a2a1c6e
Revises: e7f3f8f33731
Create Date: 2026-09-03 07:13:10.208628

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07869a2a1c6e'
down_revision: str | Sequence[str] | None = 'e7f3f8f33731'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_check_constraint(
        constraint_name='ck_no_self_subscriptions',
        table_name='subscriptions',
        condition='subscriber_id != subscribed_to_id',
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_constraint(
        constraint_name='ck_no_self_subscriptions',
        table_name='subscriptions',
        type_='check',
    )
    # ### end Alembic commands ###
