"""added created at field and updated reaction type field for post reactions

Revision ID: 149ab562360e
Revises: 271a4685e7e7
Create Date: 2026-06-08 15:42:01.896232

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '149ab562360e'
down_revision: str | Sequence[str] | None = '271a4685e7e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

reaction_type = sa.Enum(
    'positive',
    'negative',
    name='reaction_type',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    reaction_type.create(bind=op.get_bind(), checkfirst=True)

    op.add_column(
        'post_reactions',
        sa.Column('reaction_type', sa.Enum('positive', 'negative', name='reaction_type'), nullable=False),
    )
    op.add_column(
        'post_reactions',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.drop_column('post_reactions', 'is_positive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'post_reactions',
        sa.Column('is_positive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    )
    op.drop_column('post_reactions', 'created_at')
    op.drop_column('post_reactions', 'reaction_type')
    reaction_type.drop(bind=op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
