"""added post reacton model and updated post model

Revision ID: 271a4685e7e7
Revises: bb499000bd4a
Create Date: 2026-06-05 18:02:10.710801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '271a4685e7e7'
down_revision: str | Sequence[str] | None = 'bb499000bd4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post_reactions',
        sa.Column('post_id', sa.Uuid(), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('is_positive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('post_id', 'channel_id', name='unique_channel_post_reaction'),
    )
    op.add_column('posts', sa.Column('channel_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'channels', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.drop_column('posts', 'channel_id')
    op.drop_table('post_reactions')
    # ### end Alembic commands ###
