"""added new post index for pagination

Revision ID: 2b98fca544c4
Revises: e7ed8dcb5015
Create Date: 2026-06-25 17:45:53.475296

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b98fca544c4'
down_revision: str | Sequence[str] | None = 'e7ed8dcb5015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_composite_channel_id_created_at_id', 'posts', ['channel_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_channel_id_created_at_id', table_name='posts')
    # ### end Alembic commands ###
