"""updated videos ck for uploading status and updated s3_key type

Revision ID: 311aa521d7a0
Revises: 07869a2a1c6e
Create Date: 2026-09-09 09:25:43.816150

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '311aa521d7a0'
down_revision: str | Sequence[str] | None = '07869a2a1c6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 's3_key', existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_constraint(
        constraint_name='ck_upload_status',
        table_name='videos',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_upload_status',
        table_name='videos',
        condition="upload_status IN ('pending', 'uploading', 'completed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 's3_key', existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_constraint(
        constraint_name='ck_upload_status',
        table_name='videos',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_upload_status',
        table_name='videos',
        condition="upload_status IN ('uploading', 'completed')",
    )
    # ### end Alembic commands ###
