"""new videos index for sorting by views_count

Revision ID: 312e1165e700
Revises: 5b0f999c3bfa
Create Date: 2026-08-10 17:48:43.466254

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '312e1165e700'
down_revision: str | Sequence[str] | None = '5b0f999c3bfa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_videos_composite_channel_id_views_count_id', 'videos', ['channel_id', 'views_count', 'id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_composite_channel_id_views_count_id', table_name='videos')
    # ### end Alembic commands ###
