"""new PostCommentORM index

Revision ID: 338f4ffdb86a
Revises: b5300601325b
Create Date: 2026-06-27 18:20:08.563045

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '338f4ffdb86a'
down_revision: str | Sequence[str] | None = 'b5300601325b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_composite_id_post_id', 'post_comments', ['id', 'post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_id_post_id', table_name='post_comments')
    # ### end Alembic commands ###
