"""new index for playlist_items for added_at filtering and pagination

Revision ID: 33915503c5ae
Revises: fdea635603ab
Create Date: 2026-08-02 14:48:15.051494

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33915503c5ae'
down_revision: str | Sequence[str] | None = 'fdea635603ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_playlist_items_composite_added_at_filter',
        'playlist_items',
        ['playlist_id', 'created_at', 'video_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlist_items_composite_added_at_filter', table_name='playlist_items')
    # ### end Alembic commands ###
