"""new video thumbnail column

Revision ID: 371024c82524
Revises: 311aa521d7a0
Create Date: 2026-09-14 11:33:21.709093

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '371024c82524'
down_revision: str | Sequence[str] | None = '311aa521d7a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_s3_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'videos', ['thumbnail_s3_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_thumbnail_s3_key_key', 'videos', type_='unique')
    op.drop_column('videos', 'thumbnail_s3_key')
    # ### end Alembic commands ###
