"""new files_cleanup table

Revision ID: 3fea30be9a3b
Revises: 4361ab52d026
Create Date: 2026-10-06 14:24:50.722515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fea30be9a3b'
down_revision: str | Sequence[str] | None = '4361ab52d026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files_cleanup',
        sa.Column('s3_key', sa.String(length=255), nullable=False),
        sa.Column('bucket', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('s3_key', 'bucket', name='uq_file_cleanup'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_cleanup')
    # ### end Alembic commands ###
