"""added deleted_at column for channels

Revision ID: 4361ab52d026
Revises: 371024c82524
Create Date: 2026-09-25 15:55:28.856648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4361ab52d026'
down_revision: str | Sequence[str] | None = '371024c82524'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'channels', sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'deleted_at')
    # ### end Alembic commands ###
