"""New text fields max length constraints and unique constraint for videos id

Revision ID: 50ae3f828025
Revises: a64dd3a3e041
Create Date: 2026-07-16 04:40:09.675483

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50ae3f828025'
down_revision: str | Sequence[str] | None = 'a64dd3a3e041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name='ck_posts_text_max_length',
        table_name='posts',
        condition='char_length(text) <= 5000',
    )
    op.create_check_constraint(
        constraint_name='ck_post_comments_text_max_length',
        table_name='post_comments',
        condition='char_length(text) <= 10000',
    )
    op.create_check_constraint(
        constraint_name='ck_channels_description_max_length',
        table_name='channels',
        condition='char_length(description) <= 1000',
    )
    op.create_check_constraint(
        constraint_name='ck_videos_description_max_length',
        table_name='videos',
        condition='char_length(description) <= 5000',
    )
    op.create_unique_constraint(None, 'videos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_constraint('ck_videos_description_max_length', 'videos', type_='check')
    op.drop_constraint('ck_channels_description_max_length', 'channels', type_='check')
    op.drop_constraint('ck_post_comments_text_max_length', 'post_comments', type_='check')
    op.drop_constraint('ck_posts_text_max_length', 'posts', type_='check')
    # ### end Alembic commands ###
