"""removed useless indexes for post_comments and video_comments

Revision ID: 53818af38555
Revises: 797d3a4cabc3
Create Date: 2026-08-07 18:03:07.498074

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53818af38555'
down_revision: str | Sequence[str] | None = '797d3a4cabc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comments_composite_id_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_video_comments_composite_id_video_id'), table_name='video_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_video_comments_composite_id_video_id'), 'video_comments', ['id', 'video_id'], unique=False)
    op.create_index(op.f('ix_post_comments_composite_id_post_id'), 'post_comments', ['id', 'post_id'], unique=False)
    # ### end Alembic commands ###
