"""updated video_views table, new views_count column for videos table

Revision ID: 542d131dbbc8
Revises: 6b9c9211fc0b
Create Date: 2026-08-05 19:25:55.996086

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '542d131dbbc8'
down_revision: str | Sequence[str] | None = '6b9c9211fc0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_views', sa.Column('anonymous_id', sa.Uuid(), nullable=True))
    op.add_column('video_views', sa.Column('views_count', sa.Integer(), server_default='1', nullable=False))
    op.alter_column(
        'video_views',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text('CURRENT_DATE'),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        'unique_video_views_anonymous_view',
        'video_views',
        ['video_id', 'anonymous_id', 'created_at'],
        unique=True,
        postgresql_where=sa.text('anonymous_id IS NOT NULL'),
    )
    op.create_index(
        'unique_video_views_channel_view',
        'video_views',
        ['video_id', 'channel_id', 'created_at'],
        unique=True,
        postgresql_where=sa.text('channel_id IS NOT NULL'),
    )
    op.add_column('videos', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views_count')
    op.drop_index(
        'unique_video_views_channel_view', table_name='video_views', postgresql_where=sa.text('channel_id IS NOT NULL')
    )
    op.drop_index(
        'unique_video_views_anonymous_view',
        table_name='video_views',
        postgresql_where=sa.text('anonymous_id IS NOT NULL'),
    )
    op.alter_column(
        'video_views',
        'created_at',
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_column('video_views', 'views_count')
    op.drop_column('video_views', 'anonymous_id')
    # ### end Alembic commands ###
