"""new video_comment_reactions table

Revision ID: 5b0f999c3bfa
Revises: 84acd0f01390
Create Date: 2026-08-09 15:51:54.934995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b0f999c3bfa'
down_revision: str | Sequence[str] | None = '84acd0f01390'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'video_comment_reactions',
        sa.Column('video_comment_id', sa.Uuid(), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('reaction_type', sa.String(length=8), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            "reaction_type IN ('positive', 'negative')", name='ck_video_comment_reactions_reaction_type'
        ),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['video_comment_id'], ['video_comments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('video_comment_id', 'channel_id', name='uq_channel_video_comment_reaction'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_comment_reactions')
    # ### end Alembic commands ###
