"""added subscriptions model

Revision ID: 6ac7fbeda027
Revises: 149ab562360e
Create Date: 2026-06-08 18:29:14.782770

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ac7fbeda027'
down_revision: str | Sequence[str] | None = '149ab562360e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscriptions',
        sa.Column('subscriber_id', sa.Uuid(), nullable=False),
        sa.Column('subscribed_to_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['subscribed_to_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['subscriber_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('subscriber_id', 'subscribed_to_id', name='unique_channel_subscription'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
