"""new video_history_items_composite_added_at_filter for video_history_items

Revision ID: 6b9c9211fc0b
Revises: 0353f3f55f7a
Create Date: 2026-08-05 15:13:45.470605

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b9c9211fc0b'
down_revision: str | Sequence[str] | None = '0353f3f55f7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_video_history_items_composite_added_at_filter',
        'video_history_items',
        ['channel_id', 'created_at', 'video_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_history_items_composite_added_at_filter', table_name='video_history_items')
    # ### end Alembic commands ###
