"""New video_comments table

Revision ID: 797d3a4cabc3
Revises: 542d131dbbc8
Create Date: 2026-08-07 15:58:34.036259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '797d3a4cabc3'
down_revision: str | Sequence[str] | None = '542d131dbbc8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'video_comments',
        sa.Column('video_id', sa.String(length=11), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('reply_comment_id', sa.Uuid(), server_default=sa.text('NULL'), nullable=True),
        sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('reply_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(text) <= 10000', name='ck_video_comments_text_max_length'),
        sa.CheckConstraint('reply_level IN (0, 1)', name='ck_video_comments_reply_level'),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['reply_comment_id'],
            ['video_comments.id'],
        ),
        sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_video_comments_composite_comments',
        'video_comments',
        ['video_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    op.create_index('ix_video_comments_composite_id_video_id', 'video_comments', ['id', 'video_id'], unique=False)
    op.create_index(
        'ix_video_comments_composite_replies',
        'video_comments',
        ['reply_comment_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_comments_composite_replies', table_name='video_comments')
    op.drop_index('ix_video_comments_composite_id_video_id', table_name='video_comments')
    op.drop_index('ix_video_comments_composite_comments', table_name='video_comments')
    op.drop_table('video_comments')
    # ### end Alembic commands ###
