"""New playlists and playlist_items tables

Revision ID: 83a8fa43252c
Revises: df0148b0b6bf
Create Date: 2026-07-23 11:22:10.555115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83a8fa43252c'
down_revision: str | Sequence[str] | None = 'df0148b0b6bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'playlists',
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('privacy_status', sa.String(length=10), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("privacy_status IN ('public', 'private')", name='ck_playlists_privacy_status'),
        sa.CheckConstraint('char_length(description) <= 5000', name='ck_playlists_description_max_length'),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'playlist_items',
        sa.Column('playlist_id', sa.Uuid(), nullable=False),
        sa.Column('video_id', sa.String(length=11), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('playlist_id', 'video_id', name='unique_playlist_item'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_items')
    op.drop_table('playlists')
    # ### end Alembic commands ###
