"""updated reply_level check constraint for posts and videos

Revision ID: 84acd0f01390
Revises: 53818af38555
Create Date: 2026-08-08 18:45:26.732048

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84acd0f01390'
down_revision: str | Sequence[str] | None = '53818af38555'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='ck_reply_level',
        table_name='post_comments',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_reply_level',
        table_name='post_comments',
        condition='reply_level >= 0',
    )
    op.drop_constraint(
        constraint_name='ck_video_comments_reply_level',
        table_name='video_comments',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_video_comments_reply_level',
        table_name='video_comments',
        condition='reply_level >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='ck_reply_level',
        table_name='post_comments',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_reply_level',
        table_name='post_comments',
        condition='reply_level IN (0, 1)',
    )
    op.drop_constraint(
        constraint_name='ck_video_comments_reply_level',
        table_name='video_comments',
        type_='check',
    )
    op.create_check_constraint(
        constraint_name='ck_video_comments_reply_level',
        table_name='video_comments',
        condition='reply_level IN (0, 1)',
    )
    # ### end Alembic commands ###
