"""Added videos model

Revision ID: a64dd3a3e041
Revises: ad4144ddf44a
Create Date: 2026-07-09 19:04:17.920031

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a64dd3a3e041'
down_revision: str | Sequence[str] | None = 'ad4144ddf44a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'videos',
        sa.Column('id', sa.String(length=11), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('privacy_status', sa.String(length=10), nullable=False),
        sa.Column('is_reported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('upload_id', sa.String(), server_default=sa.text('NULL'), nullable=True),
        sa.Column('s3_key', sa.String(length=255), nullable=False),
        sa.Column('upload_status', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]{11}$'"),
        sa.CheckConstraint("privacy_status IN ('public', 'unlisted', 'private')", name='ck_privacy_status'),
        sa.CheckConstraint("upload_status IN ('uploading', 'completed')", name='ck_upload_status'),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('s3_key'),
        sa.UniqueConstraint('upload_id'),
    )
    op.create_index('ix_composite_upload_id_s3_key', 'videos', ['upload_id', 's3_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_upload_id_s3_key', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
