"""Added avatar column for channels model

Revision ID: ad4144ddf44a
Revises: 338f4ffdb86a
Create Date: 2026-07-04 18:31:15.124044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad4144ddf44a'
down_revision: str | Sequence[str] | None = '338f4ffdb86a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'channels', sa.Column('avatar_s3_key', sa.String(length=255), server_default=sa.text('NULL'), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'avatar_s3_key')
    # ### end Alembic commands ###
