"""New composite index for playlists

Revision ID: b0bde540358e
Revises: fb5243b1ad45
Create Date: 2026-07-29 14:38:50.143870

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0bde540358e'
down_revision: str | Sequence[str] | None = 'fb5243b1ad45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_playlists_composite_channel_id_created_at_id', 'playlists', ['channel_id', 'created_at', 'id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlists_composite_channel_id_created_at_id', table_name='playlists')
    # ### end Alembic commands ###
