"""added new post comment reaction ORM model

Revision ID: b5300601325b
Revises: 2b98fca544c4
Create Date: 2026-06-27 14:38:52.996412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5300601325b'
down_revision: str | Sequence[str] | None = '2b98fca544c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

reaction_type = sa.Enum(
    'positive',
    'negative',
    name='reaction_type',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post_comment_reactions',
        sa.Column('post_comment_id', sa.Uuid(), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('reaction_type', sa.String(length=8), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("reaction_type IN ('positive', 'negative')"),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_comment_id'], ['post_comments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('post_comment_id', 'channel_id', name='unique_channel_post_comment_reaction'),
    )
    op.alter_column(
        'post_reactions',
        'reaction_type',
        existing_type=postgresql.ENUM('positive', 'negative', name='reaction_type'),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.create_check_constraint(
        constraint_name='post_reactions_reaction_type_check',
        table_name='post_reactions',
        condition="reaction_type IN ('positive', 'negative')",
    )
    reaction_type.drop(bind=op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    reaction_type.create(bind=op.get_bind(), checkfirst=True)
    op.drop_constraint(
        constraint_name='post_reactions_reaction_type_check',
        table_name='post_reactions',
        type_='check',
    )
    op.alter_column(
        'post_reactions',
        'reaction_type',
        existing_type=sa.String(length=8),
        type_=postgresql.ENUM('positive', 'negative', name='reaction_type'),
        existing_nullable=False,
        postgresql_using='reaction_type::reaction_type',
    )
    op.drop_table('post_comment_reactions')
    # ### end Alembic commands ###
