"""new oauth_accounts table, update channels password type

Revision ID: c1c7b174880f
Revises: 312e1165e700
Create Date: 2026-08-26 17:20:57.118564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1c7b174880f'
down_revision: str | Sequence[str] | None = '312e1165e700'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'oauth_accounts',
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('provider_uid', sa.String(), nullable=False),
        sa.Column('provider', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('channel_id', 'provider', name='uq_channel_provider'),
        sa.UniqueConstraint('provider_uid', 'provider', name='uq_provider_uid'),
    )
    op.alter_column('channels', 'password_hash', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'password_hash', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
