"""added indexes to subsciptions model

Revision ID: c6d30aff151c
Revises: 6ac7fbeda027
Create Date: 2026-06-15 22:11:10.344076

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6d30aff151c'
down_revision: str | Sequence[str] | None = '6ac7fbeda027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_composite_subscribed_to_id_created_at_id',
        'subscriptions',
        ['subscribed_to_id', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(
        'ix_composite_subscriber_id_created_at_id', 'subscriptions', ['subscriber_id', 'created_at', 'id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_subscriber_id_created_at_id', table_name='subscriptions')
    op.drop_index('ix_composite_subscribed_to_id_created_at_id', table_name='subscriptions')
    # ### end Alembic commands ###
