"""New video_reactions table and updated indexes

Revision ID: df0148b0b6bf
Revises: 50ae3f828025
Create Date: 2026-07-18 15:56:37.778751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df0148b0b6bf'
down_revision: str | Sequence[str] | None = '50ae3f828025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'video_reactions',
        sa.Column('video_id', sa.String(length=11), nullable=False),
        sa.Column('channel_id', sa.Uuid(), nullable=False),
        sa.Column('reaction_type', sa.String(length=8), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("reaction_type IN ('positive', 'negative')", name='ck_video_reactions_type'),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('video_id', 'channel_id', name='unique_channel_video_reaction'),
    )
    op.drop_index(op.f('ix_composite_id_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_composite_post_id_reply_level_created_at_id'), table_name='post_comments')
    op.drop_index(op.f('ix_composite_reply_comment_id_reply_level_created_at_id'), table_name='post_comments')
    op.create_index(
        'ix_post_comments_composite_comments',
        'post_comments',
        ['post_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    op.create_index('ix_post_comments_composite_id_post_id', 'post_comments', ['id', 'post_id'], unique=False)
    op.create_index(
        'ix_post_comments_composite_replies',
        'post_comments',
        ['reply_comment_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(
        'ix_posts_composite_channel_id_created_at_id', 'posts', ['channel_id', 'created_at', 'id'], unique=False
    )
    op.drop_index(op.f('ix_composite_subscribed_to_id_created_at_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_composite_subscriber_id_created_at_id'), table_name='subscriptions')
    op.create_index(
        'ix_subscriptions_composite_subscribers',
        'subscriptions',
        ['subscribed_to_id', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(
        'ix_subscriptions_composite_subscriptions', 'subscriptions', ['subscriber_id', 'created_at', 'id'], unique=False
    )
    op.drop_index(op.f('ix_composite_upload_id_s3_key'), table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_composite_upload_id_s3_key'), 'videos', ['upload_id', 's3_key'], unique=False)
    op.drop_index('ix_subscriptions_composite_subscriptions', table_name='subscriptions')
    op.drop_index('ix_subscriptions_composite_subscribers', table_name='subscriptions')
    op.create_index(
        op.f('ix_composite_subscriber_id_created_at_id'),
        'subscriptions',
        ['subscriber_id', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_composite_subscribed_to_id_created_at_id'),
        'subscriptions',
        ['subscribed_to_id', 'created_at', 'id'],
        unique=False,
    )
    op.drop_index('ix_posts_composite_channel_id_created_at_id', table_name='posts')
    op.drop_index('ix_post_comments_composite_replies', table_name='post_comments')
    op.drop_index('ix_post_comments_composite_id_post_id', table_name='post_comments')
    op.drop_index('ix_post_comments_composite_comments', table_name='post_comments')
    op.create_index(
        op.f('ix_composite_reply_comment_id_reply_level_created_at_id'),
        'post_comments',
        ['reply_comment_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_composite_post_id_reply_level_created_at_id'),
        'post_comments',
        ['post_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    op.create_index(op.f('ix_composite_id_post_id'), 'post_comments', ['id', 'post_id'], unique=False)
    op.drop_table('video_reactions')
    # ### end Alembic commands ###
