"""added new post comment index for pagination

Revision ID: e307820a15b8
Revises: ed627757b1b3
Create Date: 2026-06-21 17:53:11.244130

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e307820a15b8'
down_revision: str | Sequence[str] | None = 'ed627757b1b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_composite_post_id_reply_level_created_at_id',
        'post_comments',
        ['post_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_post_id_reply_level_created_at_id', table_name='post_comments')
    # ### end Alembic commands ###
