"""added new post comment index for replies pagination

Revision ID: e7ed8dcb5015
Revises: e307820a15b8
Create Date: 2026-06-25 15:44:35.438521

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7ed8dcb5015'
down_revision: str | Sequence[str] | None = 'e307820a15b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_composite_reply_comment_id_reply_level_created_at_id',
        'post_comments',
        ['reply_comment_id', 'reply_level', 'created_at', 'id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_composite_reply_comment_id_reply_level_created_at_id', table_name='post_comments')
    # ### end Alembic commands ###
