"""new checkconstraint for provider column in oauth_accounts table

Revision ID: e7f3f8f33731
Revises: c1c7b174880f
Create Date: 2026-09-01 01:32:31.971052

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7f3f8f33731'
down_revision: str | Sequence[str] | None = 'c1c7b174880f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name='ck_provider',
        table_name='oauth_accounts',
        condition="provider IN ('google', 'github')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name='ck_provider',
        table_name='oauth_accounts',
        type_='check',
    )
    # ### end Alembic commands ###
