"""new created_at column for playlist_items table and new privacy status for playlists table

Revision ID: fdea635603ab
Revises: b0bde540358e
Create Date: 2026-08-01 11:10:42.405496

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdea635603ab'
down_revision: str | Sequence[str] | None = 'b0bde540358e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'playlist_items',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.drop_constraint(constraint_name='ck_playlists_privacy_status', table_name='playlists', type_='check')
    op.create_check_constraint(
        constraint_name='ck_playlists_privacy_status',
        table_name='playlists',
        condition="privacy_status IN ('public', 'unlisted', 'private')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'created_at')
    op.drop_constraint(constraint_name='ck_playlists_privacy_status', table_name='playlists', type_='check')
    op.create_check_constraint(
        constraint_name='ck_playlists_privacy_status',
        table_name='playlists',
        condition="privacy_status IN ('public', 'private')",
    )
    # ### end Alembic commands ###
